# fp = open("students.txt", 'w')
# fp.write('Hello World')
# fp.close()
fp = open("students.txt", "r")
fp.seek(13)
data = fp.readline()
print(data)
fp.seek(0)
print(fp.readlines())
fp.seek(0)
print(fp.read(8))
